# Generated by Django 4.1 on 2022-08-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "common_name",
                    models.CharField(max_length=30, verbose_name="Common Name"),
                ),
                ("photo_link", models.URLField(blank=True)),
            ],
            options={"ordering": ["common_name"],},
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Issue")),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[(1, "Disease"), (2, "Insect")], default=1
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("photo_link", models.URLField(blank=True)),
                ("tree", models.ManyToManyField(through="tree.Host", to="tree.tree")),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.AddField(
            model_name="host",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tree.issue"
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tree.tree"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="host", unique_together={("tree", "issue")},
        ),
    ]
