# Generated by Django 4.1 on 2022-08-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='gallery',
            field=models.URLField(blank=True),
        ),
    ]
