# Generated by Django 4.1 on 2022-08-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0002_tree_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Pest")),
                (
                    "category",
                    models.PositiveIntegerField(
                        choices=[(1, "Disease"), (2, "Insect")], default=1
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("photo_link", models.URLField(blank=True)),
                ("tree", models.ManyToManyField(through="tree.Host", to="tree.tree")),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.AlterUniqueTogether(name="host", unique_together=set(),),
        migrations.AddField(
            model_name="host",
            name="pest",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="tree.pest"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="host", unique_together={("tree", "pest")},
        ),
        migrations.RemoveField(model_name="host", name="issue",),
        migrations.DeleteModel(name="Issue",),
    ]
