# Generated by Django 4.1 on 2022-08-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0003_pest_alter_host_unique_together_host_pest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pest",
            name="phatogen",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="tree",
            name="scientific_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Scientific Name"
            ),
        ),
        migrations.AlterField(
            model_name="pest",
            name="category",
            field=models.PositiveIntegerField(
                choices=[(1, "Disease"), (2, "Insect"), (3, "Weed")], default=1
            ),
        ),
    ]
