# Generated by Django 4.1 on 2022-08-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0004_pest_phatogen_tree_scientific_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chm_name",
                    models.CharField(max_length=30, verbose_name="Chemical Name"),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Brand Name"
                    ),
                ),
                ("epa", models.URLField(blank=True, verbose_name="EPA")),
                ("photo_link", models.URLField(blank=True)),
            ],
            options={"ordering": ["chm_name"],},
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_ingredient",
                    models.CharField(max_length=30, verbose_name="Active ingredient"),
                ),
                (
                    "chemical",
                    models.ManyToManyField(through="tree.Amount", to="tree.chemical"),
                ),
            ],
            options={"ordering": ["active_ingredient"],},
        ),
        migrations.AddField(
            model_name="amount",
            name="active_ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tree.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="amount",
            name="chemical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tree.chemical"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="amount", unique_together={("chemical", "active_ingredient")},
        ),
    ]
