# Generated by Django 4.1 on 2022-08-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0005_amount_chemical_ingredient_amount_active_ingredient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concentration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.FloatField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="chemical",
            field=models.ManyToManyField(
                through="tree.Concentration", to="tree.chemical"
            ),
        ),
        migrations.DeleteModel(name="Amount",),
        migrations.AddField(
            model_name="concentration",
            name="active_ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tree.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="concentration",
            name="chemical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tree.chemical"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="concentration", unique_together={("chemical", "active_ingredient")},
        ),
    ]
