# Generated by Django 4.1 on 2022-08-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_concentration_alter_ingredient_chemical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'Fungicide'), (2, 'Grown Regulator'), (3, 'Herbicide'), (4, 'Insect Miticide'), (5, 'Insecticide'), (6, 'Nutribooster'), (7, 'Post Emergent'), (8, 'Pre Emergent')], default=1),
        ),
    ]
