# Generated by Django 4.1 on 2022-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_chemical_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='epa',
            field=models.CharField(blank=True, max_length=20, verbose_name='EPA'),
        ),
    ]
