# Generated by Django 4.1 on 2022-08-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_alter_chemical_epa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemical',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['common']},
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='chm_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='common_name',
            new_name='common',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='scientific_name',
            new_name='scientific',
        ),
        migrations.AlterField(
            model_name='concentration',
            name='percentage',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
